import type { BeginnerContent } from "./beginner";

export type DomainId = "1" | "2" | "3" | "4" | "5";

export interface Lesson {
  id: string;
  title: string;
  domain: DomainId;
  order: number;
  /** Section number for display, e.g. "1.1" */
  sectionNumber?: string;
  videoFocus: string[];
  simpleExplanation: string;
  highlightRules: { term: string; meaning: string; importance: "must" | "should" | "good" }[];
  writeDown: string;
  examTraps: { a: string; b: string }[];
  instantRecognition: { keyword: string; answer: string }[];
  threeSecondRecall: string[];
  quickAction: string;
  miniQuizIntro: string;
  teachBackPrompt: string;
  hasFullContent: boolean;
  /** Optional explicit checks; if omitted, UI shows defaults */
  endChecks?: string[];
  /** Optional; merged with autogenerated beginner copy in UI */
  beginner?: Partial<BeginnerContent>;
}

export type QuestionType =
  | "mcq"
  | "scenario"
  | "best"
  | "order"
  | "matching"
  | "acronym"
  | "pbc";

export interface QuizQuestion {
  id: string;
  lessonId: string;
  domain: DomainId;
  type: QuestionType;
  difficulty: 1 | 2 | 3 | 4 | 5;
  text: string;
  options: string[];
  /** Single-answer MCQ. Still set when `correctIndices` is used (first index). */
  correctIndex: number;
  /** When set, the learner must select exactly these option indices (order-independent). */
  correctIndices?: number[];
  explanation: string;
  wrongExplanations: string[];
  examKeyword: string;
  /** Optional deep link to supplemental material. */
  referenceUrl?: string;
}

export interface Flashcard {
  id: string;
  lessonId: string;
  front: string;
  back: string;
  cardType: "def" | "reverse" | "scenario" | "compare" | "trap";
  trap?: string;
}

export interface Lab {
  id: string;
  title: string;
  description: string;
  safeWarning: string;
  steps: string[];
  relatedLessonIds: string[];
  domain: DomainId;
}

export interface RoadmapItem {
  id: string;
  label: string;
  domain: DomainId;
  order: number;
  parentSection?: string;
}

export interface BrainNote {
  id: string;
  lessonId: string;
  topic: string;
  whatItMeans: string;
  realLife: string;
  whyMatters: string;
  examKeyword: string;
  memory: string;
  created: number;
}

export interface SpacedItem {
  cardId: string;
  nextReview: number;
  ease: number;
  interval: number;
}

export type Readiness = "not_ready" | "building" | "almost" | "exam_ready";

export interface CoachRecommendation {
  title: string;
  reason: string;
  why: string;
  type: "lesson" | "quiz" | "lab" | "flashcard" | "teach" | "break";
  targetId?: string;
}
