/**
 * Validates SECTION_ORDER lessons have playlist-backed primary YouTube IDs where expected.
 * Writes VIDEO_ALIGNMENT_REPORT.md. Run: npx tsx scripts/validate-videos.ts
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

async function main() {
  const { ORDERED_LESSON_IDS } = await import("../src/data/lessons.ts");
  const { getPrimaryMesserVideoIdForLesson } = await import("../src/data/videoLessonGroups.ts");
  const { readFileSync } = await import("node:fs");

  const videoMapSrc = readFileSync(join(root, "src", "data", "videoMap.ts"), "utf8");

  const unmappedAllowed = new Set(["2-0", "3-0", "3-iot", "4-0", "5-0"]);
  const problems: string[] = [];

  for (const id of ORDERED_LESSON_IDS) {
    const yt = getPrimaryMesserVideoIdForLesson(id);
    if (unmappedAllowed.has(id)) {
      if (yt) problems.push(`Expected ${id} to have no primary playlist row (overview / PDF-only slot), got ${yt}`);
    } else {
      if (!yt || yt.length !== 11) {
        problems.push(`Missing or invalid primary YouTube id for lesson: ${id} (got ${yt ?? "empty"})`);
      }
    }
  }

  if (!videoMapSrc.includes("youtube.com/embed/") && !videoMapSrc.includes("youtubeEmbed")) {
    problems.push("videoMap.ts should define embed URLs via youtubeEmbed (path must use /embed/)");
  }
  if (!videoMapSrc.includes("needsVideoUrl")) {
    problems.push("videoMap.ts should flag needsVideoUrl for unverified sections");
  }

  const matched = ORDERED_LESSON_IDS.filter((id) => {
    const yt = getPrimaryMesserVideoIdForLesson(id);
    return yt && yt.length === 11;
  }).length;

  const report = `# VIDEO_ALIGNMENT_REPORT

Generated by \`npx tsx scripts/validate-videos.ts\` (do not hand-edit for CI truth).

## Summary

| Metric | Value |
|--------|-------|
| Study lessons (\`ORDERED_LESSON_IDS\`) | ${ORDERED_LESSON_IDS.length} |
| Lessons with a primary playlist YouTube id (11 chars) | ${matched} |
| Overview / PDF-only slots (no single Messer topic video) | ${unmappedAllowed.size} |
| Official playlist videos (separate check) | 121 — see \`validate:messer-121\` |

## Policy

- **121 playlist videos** are modeled in \`professorMesser701Playlist.ts\` and grouped under 66 study lessons in \`videoLessonGroups.ts\`.
- No fake video IDs: every id is 11 characters when present.
- Section overviews **2-0**, **3-0**, **3-iot**, **4-0**, **5-0** intentionally have **no** dedicated playlist row — use PDF + quizzes + playlist browse.
- Embed URLs are built in code (\`getVideoForLesson\`) with \`/embed/\`.

## Mismatches

${problems.length ? problems.map((p) => `- ${p}`).join("\n") : "- None"}

## Official references

- Course: https://www.professormesser.com/security-plus/sy0-701/sy0-701-video/sy0-701-comptia-security-plus-course/
- Playlist: https://www.youtube.com/playlist?list=PLG49S3nxzAnl4QDVqK-hOnoqcSKEIDDuv
`;

  writeFileSync(join(root, "VIDEO_ALIGNMENT_REPORT.md"), report, "utf8");

  if (problems.length) {
    console.error("validate-videos: FAILED\n" + problems.join("\n"));
    process.exit(1);
  }
  console.log("validate-videos: OK —", matched, "primaries,", unmappedAllowed.size, "overview slots,", ORDERED_LESSON_IDS.length, "lessons. Wrote VIDEO_ALIGNMENT_REPORT.md");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
