/**
 * Professor Messer alignment: TOCs, lesson coverage, video mapping flags, reports.
 * Run: npx tsx scripts/validate-professor-messer-alignment.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

async function main() {
  const { SECTION_ORDER } = await import("../src/data/sectionOrder.ts");
  const { ORDERED_LESSON_IDS, lessons } = await import("../src/data/lessons.ts");
  const { getVideoForLesson } = await import("../src/data/videoMap.ts");
  const { getPrimaryMesserVideoIdForLesson, getMesserVideosForLesson } = await import("../src/data/videoLessonGroups.ts");
  const { PROFESSOR_MESSER_701_PLAYLIST } = await import("../src/data/professorMesser701Playlist.ts");
  const { MESSER_COURSE_NOTES_TOC } = await import("../src/data/messerCourseNotesToc.ts");
  const { EXAM_STUDY_GUIDE_TOC } = await import("../src/data/examStudyGuideToc.ts");
  const { PRACTICE_EXAMS_BOOK_TOC } = await import("../src/data/practiceExamsBookToc.ts");
  const { isLessonUnlocked } = await import("../src/utils/adaptive.ts");
  const { enrichMesserCourseNotesToc } = await import("../src/utils/messerTocVideoEnrichment.ts");

  const problems: string[] = [];

  if (MESSER_COURSE_NOTES_TOC.length < 110) {
    problems.push(`Course Notes TOC too short: ${MESSER_COURSE_NOTES_TOC.length} (expected ≥110 rows)`);
  }
  if (EXAM_STUDY_GUIDE_TOC.length < 100) {
    problems.push(`Study Guide TOC too short: ${EXAM_STUDY_GUIDE_TOC.length}`);
  }
  if (PRACTICE_EXAMS_BOOK_TOC.length < 12) {
    problems.push(`Practice Exams book TOC too short: ${PRACTICE_EXAMS_BOOK_TOC.length}`);
  }

  for (const row of MESSER_COURSE_NOTES_TOC) {
    if (row.lessonId && !lessons[row.lessonId]) {
      problems.push(`Course Notes TOC ${row.tocId} references unknown lessonId ${row.lessonId}`);
    }
  }
  for (const row of EXAM_STUDY_GUIDE_TOC) {
    if (row.lessonId && !lessons[row.lessonId]) {
      problems.push(`Study Guide TOC ${row.tocId} references unknown lessonId ${row.lessonId}`);
    }
  }

  if (!isLessonUnlocked("2-4-mal", { completedLessons: [] } as never)) {
    problems.push("Hard lesson lock detected — isLessonUnlocked must stay true");
  }

  for (const v of PROFESSOR_MESSER_701_PLAYLIST) {
    if (v.videoId.length !== 11) {
      problems.push(`Invalid playlist video id length at index ${v.index}: "${v.videoId}"`);
    }
  }

  const cnPrimary = new Map<string, string>();
  for (const row of MESSER_COURSE_NOTES_TOC) {
    if (row.lessonId && row.mapStatus === "full_lesson" && !cnPrimary.has(row.lessonId)) {
      cnPrimary.set(row.lessonId, row.tocId);
    }
  }
  for (const id of ORDERED_LESSON_IDS) {
    if (!cnPrimary.has(id)) {
      problems.push(`No full_lesson Course Notes TOC primary row for lesson ${id}`);
    }
  }

  const videoRows: string[] = [];
  videoRows.push("# VIDEO_LESSON_ALIGNMENT_REPORT");
  videoRows.push("");
  videoRows.push("Generated by `scripts/validate-professor-messer-alignment.ts`.");
  videoRows.push("");
  videoRows.push("This report reflects **66 study lessons** and **121 Professor Messer playlist videos** (grouped under lessons). Primary clip = first in group.");
  videoRows.push("");
  videoRows.push("| lessonId | title | section | primary clip title | YouTube id | watch route | status |");
  videoRows.push("|---|---|---|---|---|---|---|");

  const overviewLessons = new Set(["2-0", "3-0", "3-iot", "4-0", "5-0"]);

  let matched = 0;
  let needsVerification = 0;
  let overviewSlots = 0;
  let multiClip = 0;

  for (const id of ORDERED_LESSON_IDS) {
    const L = lessons[id]!;
    const v = getVideoForLesson(id);
    const yt = getPrimaryMesserVideoIdForLesson(id) ?? "";
    const n = getMesserVideosForLesson(id).length;
    if (n > 1) multiClip++;
    const status =
      yt && yt.length === 11 ? "primary_matched"
      : overviewLessons.has(id) ? "overview_pdf_slot"
      : "needs_verification";
    if (status === "primary_matched") matched++;
    if (status === "needs_verification") needsVerification++;
    if (status === "overview_pdf_slot") overviewSlots++;

    const safeTitle = (v.videoTitle || "").replace(/\|/g, "\\|");
    videoRows.push(
      `| ${id} | ${L.title.replace(/\|/g, "\\|")} | ${L.sectionNumber ?? "—"} | ${safeTitle} | ${yt || "—"} | /watch/${id} | ${status} (${n} clips) |`,
    );
  }

  videoRows.push("");
  videoRows.push("## Summary");
  videoRows.push("");
  videoRows.push(`| Study lessons | ${ORDERED_LESSON_IDS.length} |`);
  videoRows.push(`| Official playlist videos | ${PROFESSOR_MESSER_701_PLAYLIST.length} |`);
  videoRows.push(`| Lessons with a primary 11-char id | ${matched} |`);
  videoRows.push(`| Lessons needing video verification (no primary) | ${needsVerification} |`);
  videoRows.push(`| Overview PDF slots (no dedicated playlist row) | ${overviewSlots} |`);
  videoRows.push(`| Lessons with 2+ grouped clips | ${multiClip} |`);
  videoRows.push("");
  videoRows.push("## Policy");
  videoRows.push("");
  videoRows.push("- **121 videos** are enumerated in `professorMesser701Playlist.ts` and grouped in `videoLessonGroups.ts`.");
  videoRows.push("- **66 lessons** remain the study path (quizzes, PDFs, notes).");
  videoRows.push("- No fake YouTube IDs.");
  videoRows.push("- Playlist: https://www.youtube.com/playlist?list=PLG49S3nxzAnl4QDVqK-hOnoqcSKEIDDuv");
  videoRows.push("");

  writeFileSync(join(root, "VIDEO_LESSON_ALIGNMENT_REPORT.md"), videoRows.join("\n"), "utf8");

  const mapRows: string[] = [];
  mapRows.push("# FULL_TOC_TO_LESSON_MAPPING_REPORT");
  mapRows.push("");
  mapRows.push("Course Notes (Professor Messer) expected PDF TOC ↔ app lessons. No PDF body text is stored in the repo.");
  mapRows.push("");
  mapRows.push(
    "| tocId | subtopicId | objective | tocTitle | pdfPage | domain | lessonId | lessonTitle | matchedVideoId | matchedVideoTitle | videoMatchStatus | pdfCategory | mapStatus |",
  );
  mapRows.push("|---|---|---|---:|---|---|---|---|---|---|---|---|");

  for (const row of enrichMesserCourseNotesToc()) {
    const lid = row.lessonId;
    const L = lid ? lessons[lid] : undefined;
    const dom = L?.domain ?? (lid ? SECTION_ORDER.find((s) => s.id === lid)?.domain : undefined) ?? "—";
    const mvid = row.matchedVideoId && row.matchedVideoId.length === 11 ? row.matchedVideoId : "—";
    const mtitle = (row.matchedVideoTitle ?? "—").replace(/\|/g, "\\|");
    mapRows.push(
      `| ${row.tocId} | ${row.subtopicId} | ${row.objective} | ${row.title.replace(/\|/g, "\\|")} | ${row.pdfPage} | ${dom} | ${lid ?? "—"} | ${(L?.title ?? "—").replace(/\|/g, "\\|")} | ${mvid} | ${mtitle} | ${row.videoMatchStatus} | messer_course_notes | ${row.mapStatus} |`,
    );
  }

  mapRows.push("");
  mapRows.push("## Study Guide TOC (separate book)");
  mapRows.push("");
  mapRows.push("| tocId | sectionPath | title | domainHint | lessonId | mapStatus |");
  mapRows.push("|---|---|---|---|---|---|");
  for (const row of EXAM_STUDY_GUIDE_TOC) {
    mapRows.push(
      `| ${row.tocId} | ${row.sectionPath.replace(/\|/g, "\\|")} | ${row.title.replace(/\|/g, "\\|")} | ${row.domainHint} | ${row.lessonId ?? "—"} | ${row.mapStatus} |`,
    );
  }

  mapRows.push("");
  mapRows.push("## Practice Exams book TOC → in-app routes");
  mapRows.push("");
  mapRows.push("| tocId | title | pdfPage | routeHint |");
  mapRows.push("|---|---|---:|---|");
  for (const row of PRACTICE_EXAMS_BOOK_TOC) {
    mapRows.push(`| ${row.tocId} | ${row.title.replace(/\|/g, "\\|")} | ${row.pdfPage} | ${row.routeHint} |`);
  }

  writeFileSync(join(root, "FULL_TOC_TO_LESSON_MAPPING_REPORT.md"), mapRows.join("\n"), "utf8");

  const lessonPage = readFileSync(join(root, "src/pages/LessonPage.tsx"), "utf8");
  if (!lessonPage.includes("LessonPdfSourceTabs")) {
    problems.push("LessonPage should render LessonPdfSourceTabs for PDF tab UX");
  }

  if (problems.length) {
    console.error("validate-professor-messer-alignment: FAILED\n" + problems.join("\n"));
    process.exit(1);
  }

  console.log(
    "validate-professor-messer-alignment: OK — course notes TOC",
    MESSER_COURSE_NOTES_TOC.length,
    "study guide",
    EXAM_STUDY_GUIDE_TOC.length,
    "practice book",
    PRACTICE_EXAMS_BOOK_TOC.length,
    "videos",
    ORDERED_LESSON_IDS.length,
    "wrote VIDEO_LESSON_ALIGNMENT_REPORT.md + FULL_TOC_TO_LESSON_MAPPING_REPORT.md",
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
