/**
 * Validates the full 121-video Professor Messer playlist model vs 66 study lessons.
 * Run: npx tsx scripts/validate-professor-messer-121-videos.ts
 */
import { writeFileSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

async function main() {
  const { PROFESSOR_MESSER_701_PLAYLIST } = await import("../src/data/professorMesser701Playlist.ts");
  const { MESSER_PLAYLIST_INDEX_TO_LESSON_ID, getMesserVideosForLesson, getPrimaryMesserVideoIdForLesson } = await import(
    "../src/data/videoLessonGroups.ts"
  );
  const { ORDERED_LESSON_IDS, lessons } = await import("../src/data/lessons.ts");
  const { enrichMesserCourseNotesToc } = await import("../src/utils/messerTocVideoEnrichment.ts");

  const problems: string[] = [];

  if (PROFESSOR_MESSER_701_PLAYLIST.length !== 121) {
    problems.push(`Playlist must have 121 items, got ${PROFESSOR_MESSER_701_PLAYLIST.length}`);
  }

  const seenIds = new Set<string>();
  for (const v of PROFESSOR_MESSER_701_PLAYLIST) {
    if (v.index < 1 || v.index > 121) problems.push(`Bad playlist index ${v.index}`);
    if (v.videoId.length !== 11) problems.push(`Bad video id length for index ${v.index}: ${v.videoId}`);
    if (seenIds.has(v.videoId)) problems.push(`Duplicate video id: ${v.videoId}`);
    seenIds.add(v.videoId);
  }

  if (MESSER_PLAYLIST_INDEX_TO_LESSON_ID.length !== 121) {
    problems.push(`Index→lesson map must be 121 long, got ${MESSER_PLAYLIST_INDEX_TO_LESSON_ID.length}`);
  }

  let assigned = 0;
  for (let i = 0; i < 121; i++) {
    const lid = MESSER_PLAYLIST_INDEX_TO_LESSON_ID[i];
    if (lid == null) problems.push(`Null lesson at playlist index ${i + 1}`);
    else {
      assigned++;
      if (!lessons[lid]) problems.push(`Unknown lessonId at index ${i + 1}: ${lid}`);
    }
  }
  if (assigned !== 121) problems.push(`Expected 121 assignments, got ${assigned}`);

  const lessonPage = readFileSync(join(root, "src/pages/LessonPage.tsx"), "utf8");
  const messerList = readFileSync(join(root, "src/components/LessonMesserVideoList.tsx"), "utf8");
  const watchLesson = readFileSync(join(root, "src/pages/WatchLesson.tsx"), "utf8");
  const roadmap = readFileSync(join(root, "src/pages/Roadmap.tsx"), "utf8");
  if (!lessonPage.includes("LessonMesserVideoList")) problems.push("LessonPage must import LessonMesserVideoList");
  if (!messerList.includes("More Messer videos in this section")) {
    problems.push("LessonMesserVideoList must show the More Messer videos in this section block");
  }
  if (!watchLesson.includes("useSearchParams")) problems.push("WatchLesson must support ?video= via useSearchParams");
  if (!watchLesson.includes("Next in this lesson")) problems.push("WatchLesson must offer next clip in lesson group");
  if (!roadmap.includes("Watch Messer videos")) problems.push("Roadmap must label Watch Messer videos");
  if (!roadmap.includes("formatMesserRoadmapVideoLine")) problems.push("Roadmap must show Messer video status line");

  const enriched = enrichMesserCourseNotesToc();
  const unmatchedToc = enriched.filter(
    (r) => r.videoMatchStatus === "pdf_only" && r.lessonId && !["2-0", "3-0", "3-iot", "4-0", "5-0"].includes(r.lessonId),
  );
  /** Heuristic: many pdf_only rows with clips on the lesson usually means title matcher is too weak. */
  if (unmatchedToc.length > 80) {
    problems.push(`Too many Course Notes TOC rows still pdf_only (${unmatchedToc.length}) — tighten title matching`);
  }

  const byLesson = new Map<string, number>();
  for (const id of ORDERED_LESSON_IDS) {
    byLesson.set(id, getMesserVideosForLesson(id).length);
  }
  const multi = [...byLesson.entries()].filter(([, n]) => n > 1);

  const manualReview: string[] = [];
  for (const id of ["2-0", "3-0", "3-iot", "4-0", "5-0"]) {
    if (!getPrimaryMesserVideoIdForLesson(id)) manualReview.push(`${id}: no dedicated playlist intro row — PDF + path`);
  }

  const report: string[] = [];
  report.push("# PROFESSOR_MESSER_121_VIDEO_REPORT");
  report.push("");
  report.push("Generated by `scripts/validate-professor-messer-121-videos.ts`.");
  report.push("");
  report.push("## Summary");
  report.push("");
  report.push(`| Official playlist videos (local) | ${PROFESSOR_MESSER_701_PLAYLIST.length} |`);
  report.push(`| Study lessons (SECTION_ORDER) | ${ORDERED_LESSON_IDS.length} |`);
  report.push(`| Lessons with ≥2 playlist clips | ${multi.length} |`);
  report.push(`| Unique YouTube ids | ${seenIds.size} |`);
  report.push("");
  report.push("## Lessons with multiple Messer clips");
  report.push("");
  report.push(multi.map(([id, n]) => `- **${id}** — ${n} videos (primary: ${getPrimaryMesserVideoIdForLesson(id) ?? "—"})`).join("\n"));
  report.push("");
  report.push("## Manual review (overview slots)");
  report.push("");
  report.push(manualReview.map((x) => `- ${x}`).join("\n"));
  report.push("");
  report.push("## Policy");
  report.push("");
  report.push("- All 121 playlist rows are stored in `professorMesser701Playlist.ts` (regenerate with `node scripts/write-professor-messer-playlist-ts.mjs` + yt-dlp).");
  report.push("- Grouping is in `videoLessonGroups.ts` (`MESSER_PLAYLIST_INDEX_TO_LESSON_ID`).");
  report.push("- No fake IDs — every id is scraped from the public playlist.");
  report.push("");

  writeFileSync(join(root, "PROFESSOR_MESSER_121_VIDEO_REPORT.md"), report.join("\n"), "utf8");

  if (problems.length) {
    console.error("validate-professor-messer-121-videos: FAILED\n" + problems.join("\n"));
    process.exit(1);
  }
  console.log("validate-professor-messer-121-videos: OK — wrote PROFESSOR_MESSER_121_VIDEO_REPORT.md");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
