/**
 * Full curriculum + navigation invariants (CI).
 * Run: npx tsx scripts/validate-full-curriculum.ts
 */
import { writeFileSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const problems: string[] = [];

function fail(msg: string): never {
  console.error("validate-full-curriculum:", msg);
  process.exit(1);
}

async function main() {
  const { ORDERED_LESSON_IDS, lessons } = await import("../src/data/lessons.ts");
  const { SECTION_ORDER } = await import("../src/data/sectionOrder.ts");
  const { allQuestions } = await import("../src/data/quizzes.ts");
  const { allStaticFlashcards } = await import("../src/data/flashcards.ts");
  const { VIDEO_MAP } = await import("../src/data/videoMap.ts");
  const { labs } = await import("../src/data/labs.ts");
  const { outlineLessons } = await import("../src/data/outlineLessons.ts");
  const { getPdfGuideSection } = await import("../src/data/pdfGuides/index.ts");
  const { PDF_REGISTRY } = await import("../src/data/pdfRegistry.ts");
  const { isLessonUnlocked, getLessonOrderNudge } = await import("../src/utils/adaptive.ts");

  const outlineIds = new Set(Object.keys(outlineLessons));

  if (ORDERED_LESSON_IDS.length !== SECTION_ORDER.length) {
    problems.push("ORDERED_LESSON_IDS.length !== SECTION_ORDER.length");
  }

  const seen = new Set<string>();
  for (const id of ORDERED_LESSON_IDS) {
    if (seen.has(id)) problems.push(`Duplicate ORDERED_LESSON_IDS: ${id}`);
    seen.add(id);
    if (!lessons[id]) problems.push(`ORDERED id missing from lessons: ${id}`);
  }

  for (const s of SECTION_ORDER) {
    if (ORDERED_LESSON_IDS.indexOf(s.id) < 0) problems.push(`SECTION_ORDER id not in ORDERED_LESSON_IDS: ${s.id}`);
  }

  const lessonPage = readFileSync(join(root, "src/pages/LessonPage.tsx"), "utf8");
  if (lessonPage.includes("Lesson locked")) problems.push("LessonPage still contains hard lock copy 'Lesson locked'");
  if (lessonPage.includes("isLessonUnlocked(")) problems.push("LessonPage still calls isLessonUnlocked (use soft nudge only)");
  if (lessonPage.includes("ORDERED_LESSON_IDS")) problems.push("LessonPage should not import ORDERED_LESSON_IDS for gating");

  if (!isLessonUnlocked("1-99", { completedLessons: [] } as never)) {
    problems.push("isLessonUnlocked must always return true");
  }
  if (getLessonOrderNudge("1-0", { completedLessons: [] } as never) != null) {
    problems.push("getLessonOrderNudge(1-0) should be null (first lesson)");
  }

  const rows: string[] = [];
  rows.push("# Full lesson coverage (SY0-701 / Messer order)");
  rows.push("");
  rows.push(`Generated by \`scripts/validate-full-curriculum.ts\`. Total lessons: **${ORDERED_LESSON_IDS.length}**.`);
  rows.push("");
  rows.push(
    "| # | lessonId | title | domain | outline slot | video | quiz | flashcards | lab/sim | PDF guide (notes) | PDF guide (study) | imported PDF text | status |",
  );
  rows.push("|---:|---|---|---|---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|---|");

  let i = 0;
  for (const id of ORDERED_LESSON_IDS) {
    i++;
    const L = lessons[id]!;
    const meta = SECTION_ORDER.find((s) => s.id === id);
    const domain = meta?.domain ?? L.domain;
    const qs = allQuestions().filter((q) => q.lessonId === id);
    const fc = allStaticFlashcards().filter((c) => c.lessonId === id);
    const hasLab = labs.some((lab) => lab.relatedLessonIds.includes(id));
    const vid = VIDEO_MAP[id] != null;
    const gNotes = !!getPdfGuideSection("messer-course-notes-v107", id);
    const gStudy = !!getPdfGuideSection("sy0-701-study-guide", id);
    const outlineSlot = outlineIds.has(id);
    const studyPath = L.hasFullContent || qs.length > 0 || fc.length > 0 || hasLab || gNotes || gStudy;
    if (!studyPath) problems.push(`Lesson ${id} has no clear study path`);

    const parts: string[] = [];
    if (outlineSlot) parts.push("outline");
    if (!vid) parts.push("video gap");
    if (qs.length === 0 || fc.length === 0) parts.push("quiz/cards gap");
    const status = parts.length === 0 ? "complete" : `partial: ${parts.join(", ")}`;

    rows.push(
      `| ${i} | \`${id}\` | ${L.title.replace(/\|/g, "\\|").slice(0, 72)} | ${domain} | ${outlineSlot ? "yes" : "—"} | ${vid ? "yes" : "no"} | ${qs.length} | ${fc.length} | ${hasLab ? "yes" : "—"} | ${gNotes ? "yes" : "no"} | ${gStudy ? "yes" : "no"} | IndexedDB / user import | ${status} |`,
    );
  }

  rows.push("");
  rows.push("## PDF registry");
  for (const p of PDF_REGISTRY) {
    rows.push(`- **${p.id}** (${p.type}): ${p.title}`);
  }

  if (problems.length) {
    console.error(problems.join("\n"));
    fail(`${problems.length} problem(s)`);
  }

  const outPath = join(root, "FULL_LESSON_COVERAGE_REPORT.md");
  writeFileSync(outPath, rows.join("\n") + "\n", "utf8");
  console.log("validate-full-curriculum: OK — wrote", outPath);
}

main().catch((e) => fail(e instanceof Error ? e.message : String(e)));
