/**
 * Validates Professor Messer section IDs ↔ known YouTube IDs ↔ video map coverage.
 * Writes VIDEO_ALIGNMENT_REPORT.md at repo root. Run: node scripts/validate-videos.mjs
 */
import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const orderSrc = readFileSync(join(root, "src", "data", "sectionOrder.ts"), "utf8");
const knownSrc = readFileSync(join(root, "src", "data", "knownYoutubeIds.ts"), "utf8");
const videoMapSrc = readFileSync(join(root, "src", "data", "videoMap.ts"), "utf8");

const ids = [];
const re = /\{\s*id:\s*["']([^"']+)["']/g;
let m;
while ((m = re.exec(orderSrc)) !== null) {
  if (!ids.includes(m[1])) ids.push(m[1]);
}

const known = new Map();
const reK = /"([^"]+)":\s*"([^"]*)"/g;
while ((m = reK.exec(knownSrc)) !== null) {
  const lessonId = m[1];
  const yt = m[2];
  if (yt && yt.length !== 11) {
    console.error(`validate-videos: bad YouTube id length for ${lessonId}: "${yt}"`);
    process.exit(1);
  }
  known.set(lessonId, yt);
}

const unmappedAllowed = new Set(["2-0", "5-0", "5-grc"]);
const problems = [];
for (const id of ids) {
  if (unmappedAllowed.has(id)) {
    if (known.has(id) && known.get(id)) problems.push(`Expected ${id} to stay unverified (no individual Messer video mapped in knownYoutubeIds)`);
  } else if (!known.has(id) || !known.get(id)) {
    problems.push(`Missing YouTube id for lesson: ${id}`);
  }
}

if (!videoMapSrc.includes("youtube.com/embed/") && !videoMapSrc.includes("youtubeEmbed")) {
  problems.push("videoMap.ts should define embed URLs via youtubeEmbed (path must use /embed/)");
}
if (!videoMapSrc.includes("needsVideoUrl")) {
  problems.push("videoMap.ts should flag needsVideoUrl for unverified sections");
}

const matched = ids.filter((id) => known.has(id) && known.get(id)).length;
const needsVerification = ids.filter((id) => unmappedAllowed.has(id) || !known.get(id)).length;

const report = `# VIDEO_ALIGNMENT_REPORT

Generated by \`node scripts/validate-videos.mjs\` (do not hand-edit for CI truth).

## Summary

| Metric | Value |
|--------|-------|
| Section rows in \`SECTION_ORDER\` | ${ids.length} |
| Rows with a non-empty YouTube id in \`knownYoutubeIds.ts\` | ${matched} |
| Explicitly unmapped / verification-only (2-0, 5-0, 5-grc) | ${unmappedAllowed.size} |
| Keys in known map (total lines) | ${known.size} |

## Policy

- No fake video IDs: every id is 11 characters when present.
- Section intros **2.0**, **5.0**, and block **5-grc** use \`needsVideoUrl: true\` and link to the course index until a dedicated video is confirmed.
- Embed URLs are built in code (\`getVideoForLesson\`) with \`/embed/\` — not watch URLs.

## Mismatches

${problems.length ? problems.map((p) => `- ${p}`).join("\n") : "- None"}

## Official references

- Course: https://www.professormesser.com/security-plus/sy0-701/sy0-701-video/sy0-701-comptia-security-plus-course/
- Playlist: https://www.youtube.com/playlist?list=PLG49S3nxzAnl4QDVqK-hOnoqcSKEIDDuv
`;

writeFileSync(join(root, "VIDEO_ALIGNMENT_REPORT.md"), report, "utf8");

if (problems.length) {
  console.error("validate-videos: FAILED\n" + problems.join("\n"));
  process.exit(1);
}
console.log("validate-videos: OK —", matched, "matched,", needsVerification, "verification slots,", ids.length, "sections. Wrote VIDEO_ALIGNMENT_REPORT.md");
