/**
 * Official Professor Messer SY0-701 YouTube playlist (121 items).
 * AUTO-GENERATED by scripts/write-professor-messer-playlist-ts.mjs — run yt-dlp to refresh.
 * Playlist: https://www.youtube.com/playlist?list=PLG49S3nxzAnl4QDVqK-hOnoqcSKEIDDuv
 */
export const PROFESSOR_MESSER_701_PLAYLIST_ID = "PLG49S3nxzAnl4QDVqK-hOnoqcSKEIDDuv" as const;

export type ProfessorMesserPlaylistItem = {
  index: number;
  videoId: string;
  title: string;
  objective: string | null;
  url: string;
  status: "verified";
};

export const PROFESSOR_MESSER_701_PLAYLIST: readonly ProfessorMesserPlaylistItem[] = [
  {
    "index": 1,
    "videoId": "KiEptGbnEBc",
    "title": "How to Pass Your SY0-701 Security+ Exam in 2026",
    "objective": null,
    "url": "https://www.youtube.com/watch?v=KiEptGbnEBc",
    "status": "verified"
  },
  {
    "index": 2,
    "videoId": "STM3EUvL7wg",
    "title": "Security Controls - CompTIA Security+ SY0-701 - 1.1",
    "objective": "1.1",
    "url": "https://www.youtube.com/watch?v=STM3EUvL7wg",
    "status": "verified"
  },
  {
    "index": 3,
    "videoId": "SBcDGb9l6yo",
    "title": "The CIA Triad - CompTIA Security+ SY0-701 - 1.2",
    "objective": "1.2",
    "url": "https://www.youtube.com/watch?v=SBcDGb9l6yo",
    "status": "verified"
  },
  {
    "index": 4,
    "videoId": "XxnCxPEllMg",
    "title": "Non-repudiation - CompTIA Security+ SY0-701 - 1.2",
    "objective": "1.2",
    "url": "https://www.youtube.com/watch?v=XxnCxPEllMg",
    "status": "verified"
  },
  {
    "index": 5,
    "videoId": "AhaZtj5P2a8",
    "title": "Authentication, Authorization, and Accounting - CompTIA Security+ SY0-701 - 1.2",
    "objective": "1.2",
    "url": "https://www.youtube.com/watch?v=AhaZtj5P2a8",
    "status": "verified"
  },
  {
    "index": 6,
    "videoId": "cuTVyyS5C7M",
    "title": "Gap Analysis - CompTIA Security+ SY0-701 - 1.2",
    "objective": "1.2",
    "url": "https://www.youtube.com/watch?v=cuTVyyS5C7M",
    "status": "verified"
  },
  {
    "index": 7,
    "videoId": "zC_Pndpg8-c",
    "title": "Zero Trust - CompTIA Security+ SY0-701 - 1.2",
    "objective": "1.2",
    "url": "https://www.youtube.com/watch?v=zC_Pndpg8-c",
    "status": "verified"
  },
  {
    "index": 8,
    "videoId": "YtT8q2mUM9c",
    "title": "Physical Security - CompTIA SY0-701 Security+ - 1.2",
    "objective": "1.2",
    "url": "https://www.youtube.com/watch?v=YtT8q2mUM9c",
    "status": "verified"
  },
  {
    "index": 9,
    "videoId": "X_qfMVty4ts",
    "title": "Deception and Disruption - CompTIA Security+SY0-701 - 1.2",
    "objective": "1.2",
    "url": "https://www.youtube.com/watch?v=X_qfMVty4ts",
    "status": "verified"
  },
  {
    "index": 10,
    "videoId": "48wRbMdHFVI",
    "title": "Change Management - CompTIA Security+ SY0-701 - 1.3",
    "objective": "1.3",
    "url": "https://www.youtube.com/watch?v=48wRbMdHFVI",
    "status": "verified"
  },
  {
    "index": 11,
    "videoId": "H9TYNjcpl-0",
    "title": "Technical Change Management - CompTIA Security+ SY0-701 - 1.3",
    "objective": "1.3",
    "url": "https://www.youtube.com/watch?v=H9TYNjcpl-0",
    "status": "verified"
  },
  {
    "index": 12,
    "videoId": "xHAMEF7-inQ",
    "title": "Public Key Infrastructure - CompTIA Security+ Sy0-701 - 1.4",
    "objective": "1.4",
    "url": "https://www.youtube.com/watch?v=xHAMEF7-inQ",
    "status": "verified"
  },
  {
    "index": 13,
    "videoId": "jpsc4c7lntw",
    "title": "Encrypting Data - CompTIA Security+ SY0-701 - 1.4",
    "objective": "1.4",
    "url": "https://www.youtube.com/watch?v=jpsc4c7lntw",
    "status": "verified"
  },
  {
    "index": 14,
    "videoId": "U6BWn81P5Ec",
    "title": "Key Exchange - CompTIA Security+ SY0-701 - 1.4",
    "objective": "1.4",
    "url": "https://www.youtube.com/watch?v=U6BWn81P5Ec",
    "status": "verified"
  },
  {
    "index": 15,
    "videoId": "u61J0xR_XPU",
    "title": "Encryption Technologies - CompTIA Security+ SY0-701 - 1.4",
    "objective": "1.4",
    "url": "https://www.youtube.com/watch?v=u61J0xR_XPU",
    "status": "verified"
  },
  {
    "index": 16,
    "videoId": "LfuTMzZke4g",
    "title": "Obfuscation - CompTIA Security+ SY0-701 - 1.4",
    "objective": "1.4",
    "url": "https://www.youtube.com/watch?v=LfuTMzZke4g",
    "status": "verified"
  },
  {
    "index": 17,
    "videoId": "EcGmQjl6XEo",
    "title": "Hashing and Digital Signatures - CompTIA Security+ SY0-701 - 1.4",
    "objective": "1.4",
    "url": "https://www.youtube.com/watch?v=EcGmQjl6XEo",
    "status": "verified"
  },
  {
    "index": 18,
    "videoId": "-wqU_2ToP1M",
    "title": "Blockchain Technology - CompTIA Security+ SY0-701 - 1.4",
    "objective": "1.4",
    "url": "https://www.youtube.com/watch?v=-wqU_2ToP1M",
    "status": "verified"
  },
  {
    "index": 19,
    "videoId": "cLa94BZH_9s",
    "title": "Certificates - CompTIA Security+ SY0-701 - 1.4",
    "objective": "1.4",
    "url": "https://www.youtube.com/watch?v=cLa94BZH_9s",
    "status": "verified"
  },
  {
    "index": 20,
    "videoId": "6xUH0t6ugIM",
    "title": "Threat Actors - CompTIA Security+ SY0-701 - 2.1",
    "objective": "2.1",
    "url": "https://www.youtube.com/watch?v=6xUH0t6ugIM",
    "status": "verified"
  },
  {
    "index": 21,
    "videoId": "4lAbGpTDZ18",
    "title": "Common Threat Vectors - CompTIA Security+ SY0-701 - 2.2",
    "objective": "2.2",
    "url": "https://www.youtube.com/watch?v=4lAbGpTDZ18",
    "status": "verified"
  },
  {
    "index": 22,
    "videoId": "9SD6DRCKZFU",
    "title": "Phishing - CompTIA Security+ SY0-701 - 2.2",
    "objective": "2.2",
    "url": "https://www.youtube.com/watch?v=9SD6DRCKZFU",
    "status": "verified"
  },
  {
    "index": 23,
    "videoId": "X3yoNAVuKwA",
    "title": "Impersonation - CompTIA Security+ SY0-701 - 2.2",
    "objective": "2.2",
    "url": "https://www.youtube.com/watch?v=X3yoNAVuKwA",
    "status": "verified"
  },
  {
    "index": 24,
    "videoId": "z413PV6l_Ys",
    "title": "Watering Hole Attacks - CompTIA Security+ SY0-701 - 2.2",
    "objective": "2.2",
    "url": "https://www.youtube.com/watch?v=z413PV6l_Ys",
    "status": "verified"
  },
  {
    "index": 25,
    "videoId": "akoDmeV3LQo",
    "title": "Other Social Engineering Attacks - CompTIA Security+ SY0-701 - 2.2",
    "objective": "2.2",
    "url": "https://www.youtube.com/watch?v=akoDmeV3LQo",
    "status": "verified"
  },
  {
    "index": 26,
    "videoId": "kBcTczu8FsM",
    "title": "Memory Injections - CompTIA Security+ SY0-701 - 2.3",
    "objective": "2.3",
    "url": "https://www.youtube.com/watch?v=kBcTczu8FsM",
    "status": "verified"
  },
  {
    "index": 27,
    "videoId": "0-qeeI5jTqU",
    "title": "Buffer Overflows - CompTIA Security+ SY0-701 - 2.3",
    "objective": "2.3",
    "url": "https://www.youtube.com/watch?v=0-qeeI5jTqU",
    "status": "verified"
  },
  {
    "index": 28,
    "videoId": "MKptc1lPSw8",
    "title": "Race Conditions - CompTIA Security+ SY0-701 - 2.3",
    "objective": "2.3",
    "url": "https://www.youtube.com/watch?v=MKptc1lPSw8",
    "status": "verified"
  },
  {
    "index": 29,
    "videoId": "KbtUrdBy9Yo",
    "title": "Malicious Updates - CompTIA Security+ SY0-701 - 2.3",
    "objective": "2.3",
    "url": "https://www.youtube.com/watch?v=KbtUrdBy9Yo",
    "status": "verified"
  },
  {
    "index": 30,
    "videoId": "narir8qpGq8",
    "title": "Operating System Vulnerabilities - CompTIA Security+ SY0-701 - 2.3",
    "objective": "2.3",
    "url": "https://www.youtube.com/watch?v=narir8qpGq8",
    "status": "verified"
  },
  {
    "index": 31,
    "videoId": "qFUOLkEk8AQ",
    "title": "SQL Injection - CompTIA Security+ SY0-701 - 2.3",
    "objective": "2.3",
    "url": "https://www.youtube.com/watch?v=qFUOLkEk8AQ",
    "status": "verified"
  },
  {
    "index": 32,
    "videoId": "PKgw0CLZIhE",
    "title": "Cross-site Scripting - CompTIA Security+ SY0-701 - 2.3",
    "objective": "2.3",
    "url": "https://www.youtube.com/watch?v=PKgw0CLZIhE",
    "status": "verified"
  },
  {
    "index": 33,
    "videoId": "TaTaEvqjjDM",
    "title": "Hardware Vulnerabilities - CompTIA Security+ SY0-701 - 2.3",
    "objective": "2.3",
    "url": "https://www.youtube.com/watch?v=TaTaEvqjjDM",
    "status": "verified"
  },
  {
    "index": 34,
    "videoId": "t2JrPrzRDLA",
    "title": "Virtualization Vulnerabilities - CompTIA Security+ SY0-701 - 2.3",
    "objective": "2.3",
    "url": "https://www.youtube.com/watch?v=t2JrPrzRDLA",
    "status": "verified"
  },
  {
    "index": 35,
    "videoId": "V2DCYO-sWRQ",
    "title": "Cloud-specific Vulnerabilities - CompTIA Security+ SY0-701 - 2.3",
    "objective": "2.3",
    "url": "https://www.youtube.com/watch?v=V2DCYO-sWRQ",
    "status": "verified"
  },
  {
    "index": 36,
    "videoId": "WqvCJLpwExY",
    "title": "Supply Chain Vulnerabilities - CompTIA Security+ SY0-701 - 2.3",
    "objective": "2.3",
    "url": "https://www.youtube.com/watch?v=WqvCJLpwExY",
    "status": "verified"
  },
  {
    "index": 37,
    "videoId": "NBKzlUqzVmE",
    "title": "Misconfiguration Vulnerabilities - CompTIA Security+ SY0-701 - 2.3",
    "objective": "2.3",
    "url": "https://www.youtube.com/watch?v=NBKzlUqzVmE",
    "status": "verified"
  },
  {
    "index": 38,
    "videoId": "DRfAwwdzYpU",
    "title": "Mobile Device Vulnerabilities - CompTIA Security+ SY0-701 - 2.3",
    "objective": "2.3",
    "url": "https://www.youtube.com/watch?v=DRfAwwdzYpU",
    "status": "verified"
  },
  {
    "index": 39,
    "videoId": "FDFxGLnZtoY",
    "title": "Zero-day Vulnerabilities - CompTIA Security+ SY0-701 - 2.3",
    "objective": "2.3",
    "url": "https://www.youtube.com/watch?v=FDFxGLnZtoY",
    "status": "verified"
  },
  {
    "index": 40,
    "videoId": "-eZs8wjjGGE",
    "title": "An Overview of Malware - CompTIA Security+ SY0-701 - 2.4",
    "objective": "2.4",
    "url": "https://www.youtube.com/watch?v=-eZs8wjjGGE",
    "status": "verified"
  },
  {
    "index": 41,
    "videoId": "Su8ANmAoerU",
    "title": "Viruses and Worms - CompTIA Security+ SY0-701 - 2.4",
    "objective": "2.4",
    "url": "https://www.youtube.com/watch?v=Su8ANmAoerU",
    "status": "verified"
  },
  {
    "index": 42,
    "videoId": "-VmI3xFJw78",
    "title": "Spyware and Bloatware - CompTIA Security+ SY0-701 - 2.4",
    "objective": "2.4",
    "url": "https://www.youtube.com/watch?v=-VmI3xFJw78",
    "status": "verified"
  },
  {
    "index": 43,
    "videoId": "nu27ovJ5rqw",
    "title": "Other Malware Types - CompTIA Security+ SY0-701 - 2.4",
    "objective": "2.4",
    "url": "https://www.youtube.com/watch?v=nu27ovJ5rqw",
    "status": "verified"
  },
  {
    "index": 44,
    "videoId": "oIpOuTX2HRs",
    "title": "Physical Attacks - CompTIA Security+ SY0-701 - 2.4",
    "objective": "2.4",
    "url": "https://www.youtube.com/watch?v=oIpOuTX2HRs",
    "status": "verified"
  },
  {
    "index": 45,
    "videoId": "Z7OntvK--PQ",
    "title": "Denial of Service - CompTIA Security+ SY0-701 - 2.4",
    "objective": "2.4",
    "url": "https://www.youtube.com/watch?v=Z7OntvK--PQ",
    "status": "verified"
  },
  {
    "index": 46,
    "videoId": "BoxeL5ybOXI",
    "title": "DNS Attacks - CompTIA Security+ SY0-701 - 2.4",
    "objective": "2.4",
    "url": "https://www.youtube.com/watch?v=BoxeL5ybOXI",
    "status": "verified"
  },
  {
    "index": 47,
    "videoId": "tSLqrKhUvts",
    "title": "Wireless Attacks - CompTIA Security+ SY0-701 - 2.4",
    "objective": "2.4",
    "url": "https://www.youtube.com/watch?v=tSLqrKhUvts",
    "status": "verified"
  },
  {
    "index": 48,
    "videoId": "M_Af6_8JTuo",
    "title": "On-path Attacks - CompTIA Security+ SY0-701 - 2.4",
    "objective": "2.4",
    "url": "https://www.youtube.com/watch?v=M_Af6_8JTuo",
    "status": "verified"
  },
  {
    "index": 49,
    "videoId": "ai6qS13gKRo",
    "title": "Replay Attacks - CompTIA Security+ SY0-701- 2.4",
    "objective": "2.4",
    "url": "https://www.youtube.com/watch?v=ai6qS13gKRo",
    "status": "verified"
  },
  {
    "index": 50,
    "videoId": "xDhUBQ_lnUA",
    "title": "Malicious Code - CompTIA Security+ SY0-701 - 2.4",
    "objective": "2.4",
    "url": "https://www.youtube.com/watch?v=xDhUBQ_lnUA",
    "status": "verified"
  },
  {
    "index": 51,
    "videoId": "yRSqIGjeb7s",
    "title": "Application Attacks - CompTIA Security+ SY0-701 - 2.4",
    "objective": "2.4",
    "url": "https://www.youtube.com/watch?v=yRSqIGjeb7s",
    "status": "verified"
  },
  {
    "index": 52,
    "videoId": "7aJaEQy6Yoc",
    "title": "Cryptographic Attacks - CompTIA Security+ SY0-701 - 2.4",
    "objective": "2.4",
    "url": "https://www.youtube.com/watch?v=7aJaEQy6Yoc",
    "status": "verified"
  },
  {
    "index": 53,
    "videoId": "-ZfbifHwEVE",
    "title": "Password Attacks - CompTIA Security+ SY0-701 - 2.4",
    "objective": "2.4",
    "url": "https://www.youtube.com/watch?v=-ZfbifHwEVE",
    "status": "verified"
  },
  {
    "index": 54,
    "videoId": "x72hG9GvkaQ",
    "title": "Indicators of Compromise - CompTIA Security+ SY0-701 - 2.4",
    "objective": "2.4",
    "url": "https://www.youtube.com/watch?v=x72hG9GvkaQ",
    "status": "verified"
  },
  {
    "index": 55,
    "videoId": "yDeDGCh_PDs",
    "title": "Segmentation and Access Control - CompTIA Security+ SY0-701 - 2.5",
    "objective": "2.5",
    "url": "https://www.youtube.com/watch?v=yDeDGCh_PDs",
    "status": "verified"
  },
  {
    "index": 56,
    "videoId": "Fc8ZJfmapbI",
    "title": "Mitigation Techniques - CompTIA Security+ SY0-701 - 2.5",
    "objective": "2.5",
    "url": "https://www.youtube.com/watch?v=Fc8ZJfmapbI",
    "status": "verified"
  },
  {
    "index": 57,
    "videoId": "wXoC46Qr_9Q",
    "title": "Hardening Techniques - CompTIA Security+ SY0-701 - 2.5",
    "objective": "2.5",
    "url": "https://www.youtube.com/watch?v=wXoC46Qr_9Q",
    "status": "verified"
  },
  {
    "index": 58,
    "videoId": "8qpQ8Q6xxiU",
    "title": "Cloud Infrastructures - CompTIA Security+ SY0-701 - 3.1",
    "objective": "3.1",
    "url": "https://www.youtube.com/watch?v=8qpQ8Q6xxiU",
    "status": "verified"
  },
  {
    "index": 59,
    "videoId": "jd001Hj7XWM",
    "title": "Network Infrastructure Concepts - CompTIA Security+ SY0-701 - 3.1",
    "objective": "3.1",
    "url": "https://www.youtube.com/watch?v=jd001Hj7XWM",
    "status": "verified"
  },
  {
    "index": 60,
    "videoId": "HDiNPPrGhzE",
    "title": "Other Infrastructure Concepts - CompTIA Security+ SY0-701 - 3.1",
    "objective": "3.1",
    "url": "https://www.youtube.com/watch?v=HDiNPPrGhzE",
    "status": "verified"
  },
  {
    "index": 61,
    "videoId": "Ap3Z_0ZdqpQ",
    "title": "Infrastructure Considerations - CompTIA Security+ SY0-701 - 3.1",
    "objective": "3.1",
    "url": "https://www.youtube.com/watch?v=Ap3Z_0ZdqpQ",
    "status": "verified"
  },
  {
    "index": 62,
    "videoId": "l64La1xYXL4",
    "title": "Secure Infrastructures - CompTIA Security+ SY0-701 - 3.2",
    "objective": "3.2",
    "url": "https://www.youtube.com/watch?v=l64La1xYXL4",
    "status": "verified"
  },
  {
    "index": 63,
    "videoId": "7QuYupuic3Q",
    "title": "Intrusion Prevention - CompTIA Security+ SY0-701 - 3.2",
    "objective": "3.2",
    "url": "https://www.youtube.com/watch?v=7QuYupuic3Q",
    "status": "verified"
  },
  {
    "index": 64,
    "videoId": "WlOslEy3ztg",
    "title": "Network Appliances - CompTIA Security+ SY0-701 - 3.2",
    "objective": "3.2",
    "url": "https://www.youtube.com/watch?v=WlOslEy3ztg",
    "status": "verified"
  },
  {
    "index": 65,
    "videoId": "QhLQ6J4satw",
    "title": "Port Security - CompTIA Security+ SY0-701 - 3.2",
    "objective": "3.2",
    "url": "https://www.youtube.com/watch?v=QhLQ6J4satw",
    "status": "verified"
  },
  {
    "index": 66,
    "videoId": "mq1HRM-zGtQ",
    "title": "Firewall Types - CompTIA Security+ SY0-701 - 3.2",
    "objective": "3.2",
    "url": "https://www.youtube.com/watch?v=mq1HRM-zGtQ",
    "status": "verified"
  },
  {
    "index": 67,
    "videoId": "uU3e_ntg-3g",
    "title": "Secure Communication - CompTIA Security+ SY0-701 - 3.2",
    "objective": "3.2",
    "url": "https://www.youtube.com/watch?v=uU3e_ntg-3g",
    "status": "verified"
  },
  {
    "index": 68,
    "videoId": "R0W0_gZCVzk",
    "title": "Data Types and Classifications - CompTIA Security+ SY0-701 - 3.3",
    "objective": "3.3",
    "url": "https://www.youtube.com/watch?v=R0W0_gZCVzk",
    "status": "verified"
  },
  {
    "index": 69,
    "videoId": "71RQaYQ4QSw",
    "title": "States of Data - CompTIA Security+ SY0-701 - 3.3",
    "objective": "3.3",
    "url": "https://www.youtube.com/watch?v=71RQaYQ4QSw",
    "status": "verified"
  },
  {
    "index": 70,
    "videoId": "leX_Qa7wqB4",
    "title": "Protecting Data - CompTIA Security+ SY0-701 - 3.3",
    "objective": "3.3",
    "url": "https://www.youtube.com/watch?v=leX_Qa7wqB4",
    "status": "verified"
  },
  {
    "index": 71,
    "videoId": "sb0dRaQbuBA",
    "title": "Resiliency - CompTIA Security+ SY0-701 - 3.4",
    "objective": "3.4",
    "url": "https://www.youtube.com/watch?v=sb0dRaQbuBA",
    "status": "verified"
  },
  {
    "index": 72,
    "videoId": "WGlT6-gNwqY",
    "title": "Capacity Planning - CompTIA Security+ SY0-701 - 3.4",
    "objective": "3.4",
    "url": "https://www.youtube.com/watch?v=WGlT6-gNwqY",
    "status": "verified"
  },
  {
    "index": 73,
    "videoId": "IhT7Odu4xHc",
    "title": "Recovery Testing - CompTIA Security+ SY0-701 - 3.4",
    "objective": "3.4",
    "url": "https://www.youtube.com/watch?v=IhT7Odu4xHc",
    "status": "verified"
  },
  {
    "index": 74,
    "videoId": "8mGSwRScqIM",
    "title": "Backups - CompTIA Security+ SY0-701 - 3.4",
    "objective": "3.4",
    "url": "https://www.youtube.com/watch?v=8mGSwRScqIM",
    "status": "verified"
  },
  {
    "index": 75,
    "videoId": "-EY45MimSBM",
    "title": "Power Resiliency - CompTIA Security+ SY0-701 - 3.4",
    "objective": "3.4",
    "url": "https://www.youtube.com/watch?v=-EY45MimSBM",
    "status": "verified"
  },
  {
    "index": 76,
    "videoId": "BWPJD9Eb9iE",
    "title": "Secure Baselines - CompTIA Security+ SY0-701 - 4.1",
    "objective": "4.1",
    "url": "https://www.youtube.com/watch?v=BWPJD9Eb9iE",
    "status": "verified"
  },
  {
    "index": 77,
    "videoId": "YQKbs0ug0XQ",
    "title": "Hardening Targets - CompTIA Security+ SY0-701 - 4.1",
    "objective": "4.1",
    "url": "https://www.youtube.com/watch?v=YQKbs0ug0XQ",
    "status": "verified"
  },
  {
    "index": 78,
    "videoId": "iAR6SgvtezY",
    "title": "Securing Wireless and Mobile - CompTIA Security+ SY0-701 - 4.1",
    "objective": "4.1",
    "url": "https://www.youtube.com/watch?v=iAR6SgvtezY",
    "status": "verified"
  },
  {
    "index": 79,
    "videoId": "KaqKoKNEKnE",
    "title": "Wireless Security Settings - CompTIA Security+ SY0-701 - 4.1",
    "objective": "4.1",
    "url": "https://www.youtube.com/watch?v=KaqKoKNEKnE",
    "status": "verified"
  },
  {
    "index": 80,
    "videoId": "fFvXy3WkLpA",
    "title": "Application Security - CompTIA Security+ SY0-701 - 4.1",
    "objective": "4.1",
    "url": "https://www.youtube.com/watch?v=fFvXy3WkLpA",
    "status": "verified"
  },
  {
    "index": 81,
    "videoId": "BJ2UMB4a04g",
    "title": "Asset Management - CompTIA Security+ SY0-701 - 4.2",
    "objective": "4.2",
    "url": "https://www.youtube.com/watch?v=BJ2UMB4a04g",
    "status": "verified"
  },
  {
    "index": 82,
    "videoId": "9B0mtWk_AM0",
    "title": "Vulnerability Scanning - CompTIA Security+ SY0-701 - 4.3",
    "objective": "4.3",
    "url": "https://www.youtube.com/watch?v=9B0mtWk_AM0",
    "status": "verified"
  },
  {
    "index": 83,
    "videoId": "86fruE9jkKk",
    "title": "Threat Intelligence - CompTIA Security+ SY0-701 - 4.3",
    "objective": "4.3",
    "url": "https://www.youtube.com/watch?v=86fruE9jkKk",
    "status": "verified"
  },
  {
    "index": 84,
    "videoId": "-LevHAzXgFs",
    "title": "Penetration Testing - CompTIA Security+ SY0-701 - 4.3",
    "objective": "4.3",
    "url": "https://www.youtube.com/watch?v=-LevHAzXgFs",
    "status": "verified"
  },
  {
    "index": 85,
    "videoId": "eyVy1gKCuAU",
    "title": "Analyzing Vulnerabilities - CompTIA Security+ SY0-701 - 4.3",
    "objective": "4.3",
    "url": "https://www.youtube.com/watch?v=eyVy1gKCuAU",
    "status": "verified"
  },
  {
    "index": 86,
    "videoId": "P9xakfmX70c",
    "title": "Vulnerability Remediation - CompTIA Security+ SY0-701 - 4.3",
    "objective": "4.3",
    "url": "https://www.youtube.com/watch?v=P9xakfmX70c",
    "status": "verified"
  },
  {
    "index": 87,
    "videoId": "np2WI_rM-Ok",
    "title": "Security Monitoring - CompTIA Security+ SY0-701 - 4.4",
    "objective": "4.4",
    "url": "https://www.youtube.com/watch?v=np2WI_rM-Ok",
    "status": "verified"
  },
  {
    "index": 88,
    "videoId": "nNiNTviiacU",
    "title": "Security Tools - CompTIA Security+ SY0-701 - 4.4",
    "objective": "4.4",
    "url": "https://www.youtube.com/watch?v=nNiNTviiacU",
    "status": "verified"
  },
  {
    "index": 89,
    "videoId": "VgNyh4HEqSU",
    "title": "Firewalls - CompTIA Security+ SY0-701 - 4.5",
    "objective": "4.5",
    "url": "https://www.youtube.com/watch?v=VgNyh4HEqSU",
    "status": "verified"
  },
  {
    "index": 90,
    "videoId": "I_c0D49uCwQ",
    "title": "Web Filtering - CompTIA Security+ SY0-701 - 4.5",
    "objective": "4.5",
    "url": "https://www.youtube.com/watch?v=I_c0D49uCwQ",
    "status": "verified"
  },
  {
    "index": 91,
    "videoId": "4dpTyRM6BU8",
    "title": "Operating System Security - CompTIA Security+ SY0-701 - 4.5",
    "objective": "4.5",
    "url": "https://www.youtube.com/watch?v=4dpTyRM6BU8",
    "status": "verified"
  },
  {
    "index": 92,
    "videoId": "9NAKCyOtFH0",
    "title": "Secure Protocols - CompTIA Security+ SY0-701 - 4.5",
    "objective": "4.5",
    "url": "https://www.youtube.com/watch?v=9NAKCyOtFH0",
    "status": "verified"
  },
  {
    "index": 93,
    "videoId": "v6ht9efsnRI",
    "title": "Email Security - CompTIA Security+ SY0-701 - 4.5",
    "objective": "4.5",
    "url": "https://www.youtube.com/watch?v=v6ht9efsnRI",
    "status": "verified"
  },
  {
    "index": 94,
    "videoId": "ZDJ-BLPLWq4",
    "title": "Monitoring Data - CompTIA Security+ SY0-701 - 4.5",
    "objective": "4.5",
    "url": "https://www.youtube.com/watch?v=ZDJ-BLPLWq4",
    "status": "verified"
  },
  {
    "index": 95,
    "videoId": "83pCkSSj1IQ",
    "title": "Endpoint Security - CompTIA Security+ SY0-701 - 4.5",
    "objective": "4.5",
    "url": "https://www.youtube.com/watch?v=83pCkSSj1IQ",
    "status": "verified"
  },
  {
    "index": 96,
    "videoId": "ZoOyyqhptik",
    "title": "Identity and Access Management - CompTIA Security+ SY0-701 - 4.6",
    "objective": "4.6",
    "url": "https://www.youtube.com/watch?v=ZoOyyqhptik",
    "status": "verified"
  },
  {
    "index": 97,
    "videoId": "9ANHcZwJfdQ",
    "title": "Access Controls - CompTIA Security+ SY0-701 - 4.6",
    "objective": "4.6",
    "url": "https://www.youtube.com/watch?v=9ANHcZwJfdQ",
    "status": "verified"
  },
  {
    "index": 98,
    "videoId": "MpIzA4fNWew",
    "title": "Multifactor Authentication - CompTIA Security+ SY0-701 - 4.6",
    "objective": "4.6",
    "url": "https://www.youtube.com/watch?v=MpIzA4fNWew",
    "status": "verified"
  },
  {
    "index": 99,
    "videoId": "eMOe-PLBy1k",
    "title": "Password Security - CompTIA Security+ SY0-701 - 4.6",
    "objective": "4.6",
    "url": "https://www.youtube.com/watch?v=eMOe-PLBy1k",
    "status": "verified"
  },
  {
    "index": 100,
    "videoId": "R9ojg881dLs",
    "title": "Scripting and Automation - CompTIA Security+ SY0-701 - 4.7",
    "objective": "4.7",
    "url": "https://www.youtube.com/watch?v=R9ojg881dLs",
    "status": "verified"
  },
  {
    "index": 101,
    "videoId": "X2UiMLxRdhE",
    "title": "Incident Response - CompTIA Security+ SY0-701 - 4.8",
    "objective": "4.8",
    "url": "https://www.youtube.com/watch?v=X2UiMLxRdhE",
    "status": "verified"
  },
  {
    "index": 102,
    "videoId": "CYFe16lCRMk",
    "title": "Incident Planning - CompTIA Security+ SY0-701 - 4.8",
    "objective": "4.8",
    "url": "https://www.youtube.com/watch?v=CYFe16lCRMk",
    "status": "verified"
  },
  {
    "index": 103,
    "videoId": "UtDWApdO8Zk",
    "title": "Digital Forensics - CompTIA Security+ SY0-701 - 4.8",
    "objective": "4.8",
    "url": "https://www.youtube.com/watch?v=UtDWApdO8Zk",
    "status": "verified"
  },
  {
    "index": 104,
    "videoId": "EDru1LTYDJw",
    "title": "Log Data - CompTIA Security+ SY0-701 - 4.9",
    "objective": "4.9",
    "url": "https://www.youtube.com/watch?v=EDru1LTYDJw",
    "status": "verified"
  },
  {
    "index": 105,
    "videoId": "5kY9kvzeWjA",
    "title": "Security Policies - CompTIA Security+ SY0-701 - 5.1",
    "objective": "5.1",
    "url": "https://www.youtube.com/watch?v=5kY9kvzeWjA",
    "status": "verified"
  },
  {
    "index": 106,
    "videoId": "jBvdRpXaomk",
    "title": "Security Standards - CompTIA Security+ SY0-701 - 5.1",
    "objective": "5.1",
    "url": "https://www.youtube.com/watch?v=jBvdRpXaomk",
    "status": "verified"
  },
  {
    "index": 107,
    "videoId": "vJINnOZyQNg",
    "title": "Security Procedures - CompTIA Security+ SY0-701 - 5.1",
    "objective": "5.1",
    "url": "https://www.youtube.com/watch?v=vJINnOZyQNg",
    "status": "verified"
  },
  {
    "index": 108,
    "videoId": "4tGFraaP48Q",
    "title": "Security Considerations - CompTIA Security+ SY0-701 - 5.1",
    "objective": "5.1",
    "url": "https://www.youtube.com/watch?v=4tGFraaP48Q",
    "status": "verified"
  },
  {
    "index": 109,
    "videoId": "gxNi-04yP8Q",
    "title": "Data Roles and Responsibilities - CompTIA Security+ SY0-701 - 5.1",
    "objective": "5.1",
    "url": "https://www.youtube.com/watch?v=gxNi-04yP8Q",
    "status": "verified"
  },
  {
    "index": 110,
    "videoId": "cLhUMoQS1a8",
    "title": "Risk Management - CompTIA Security+ SY0-701 - 5.2",
    "objective": "5.2",
    "url": "https://www.youtube.com/watch?v=cLhUMoQS1a8",
    "status": "verified"
  },
  {
    "index": 111,
    "videoId": "Ykx7t54y-oo",
    "title": "Risk Analysis - CompTIA Security+ SY0-701 - 5.2",
    "objective": "5.2",
    "url": "https://www.youtube.com/watch?v=Ykx7t54y-oo",
    "status": "verified"
  },
  {
    "index": 112,
    "videoId": "pmyuWY7Pbag",
    "title": "Risk Management Strategies - CompTIA Security+ SY0-701 - 5.2",
    "objective": "5.2",
    "url": "https://www.youtube.com/watch?v=pmyuWY7Pbag",
    "status": "verified"
  },
  {
    "index": 113,
    "videoId": "myI-v3mj7Kc",
    "title": "Business Impact Analysis - CompTIA Security+ SY0-701 - 5.2",
    "objective": "5.2",
    "url": "https://www.youtube.com/watch?v=myI-v3mj7Kc",
    "status": "verified"
  },
  {
    "index": 114,
    "videoId": "13KNjPexnEI",
    "title": "Third-party Risk Assessment - CompTIA Security+ SY0-701 - 5.3",
    "objective": "5.3",
    "url": "https://www.youtube.com/watch?v=13KNjPexnEI",
    "status": "verified"
  },
  {
    "index": 115,
    "videoId": "HSZxjj1YAh8",
    "title": "Agreement Types - CompTIA Security+ SY0-701 - 5.3",
    "objective": "5.3",
    "url": "https://www.youtube.com/watch?v=HSZxjj1YAh8",
    "status": "verified"
  },
  {
    "index": 116,
    "videoId": "IjJf4jLtONQ",
    "title": "Compliance - CompTIA Security+ SY0-701 - 5.4",
    "objective": "5.4",
    "url": "https://www.youtube.com/watch?v=IjJf4jLtONQ",
    "status": "verified"
  },
  {
    "index": 117,
    "videoId": "WGXrbAh0LUI",
    "title": "Privacy - CompTIA Security+ SY0-701 - 5.4",
    "objective": "5.4",
    "url": "https://www.youtube.com/watch?v=WGXrbAh0LUI",
    "status": "verified"
  },
  {
    "index": 118,
    "videoId": "uo2Yw720mv4",
    "title": "Audits and Assessments - CompTIA Security+ SY0-701 - 5.5",
    "objective": "5.5",
    "url": "https://www.youtube.com/watch?v=uo2Yw720mv4",
    "status": "verified"
  },
  {
    "index": 119,
    "videoId": "wEMzVfwBiWY",
    "title": "Penetration Tests - CompTIA Security+ SY0-701 - 5.5",
    "objective": "5.5",
    "url": "https://www.youtube.com/watch?v=wEMzVfwBiWY",
    "status": "verified"
  },
  {
    "index": 120,
    "videoId": "W_Npxwk4fbI",
    "title": "Security Awareness - CompTIA Security+ SY0-701 - 5.6",
    "objective": "5.6",
    "url": "https://www.youtube.com/watch?v=W_Npxwk4fbI",
    "status": "verified"
  },
  {
    "index": 121,
    "videoId": "WQRZMMLUkGE",
    "title": "User Training - CompTIA Security+ SY0-701 - 5.6",
    "objective": "5.6",
    "url": "https://www.youtube.com/watch?v=WQRZMMLUkGE",
    "status": "verified"
  }
] as const;

export function messerPlaylistVideoById(videoId: string): ProfessorMesserPlaylistItem | undefined {
  return PROFESSOR_MESSER_701_PLAYLIST.find((v) => v.videoId === videoId);
}

/** Extract X.Y from Messer-style titles when present. */
export function parseObjectiveFromMesserTitle(title: string): string | null {
  const m = title.match(/-\s*(\d+\.\d+)\s*$/);
  return m ? m[1] : null;
}
